#!/usr/bin/env python3
import argparse
import os
import sys
from time import sleep

import grpc

# Import P4Runtime lib from parent utils dir
# Probably there's a better way of doing this.
sys.path.append(
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 '../../utils/'))
import p4runtime_lib.bmv2
import p4runtime_lib.helper
from p4runtime_lib.switch import ShutdownAllSwitchConnections



def writeTunnelRules(p4info_helper, ingress_sw, egress_sw, tunnel_id,#定义隧道规则
                     dst_eth_addr, dst_ip_addr):
    if(ingress_sw.name=='s1' and egress_sw.name=='s2'):
        WITCH_TO_SWITCH_PORT=3
        if(dst_ip_addr=="10.0.2.2"):
            WITCH_TO_HOST_PORT=2
        else:
            WITCH_TO_HOST_PORT=1
    elif(ingress_sw.name=='s2'and egress_sw.name=='s1'):
        WITCH_TO_SWITCH_PORT=3
        if(dst_ip_addr=="10.0.1.1"):
            WITCH_TO_HOST_PORT=2
        else:
            WITCH_TO_HOST_PORT=1
#根据交换机链接关系选择端口

    table_entry = p4info_helper.buildTableEntry(#p4info_helper解析器将规则转化为P4Runtime能够识别的形式
        table_name="MyIngress.ipv4_lpm",#表名
        match_fields={#匹配域
            "hdr.ipv4.dstAddr": (dst_ip_addr, 32)#若hdr.ipv4.dstAddr与dst_ip_addr匹配则执行动作，32是掩码
        },
        action_name="MyIngress.ipv4_forward",#动作名
        action_params={#传入参数
            "dstAddr":dst_eth_addr,
            "port":WITCH_TO_SWITCH_PORT,
        })
    ingress_sw.WriteTableEntry(table_entry)#将生成的匹配动作表项加入交换机
    table_entry = p4info_helper.buildTableEntry(#p4info_helper解析器将规则转化为P4Runtime能够识别的形式
        table_name="MyIngress.ipv4_lpm",#表名
        match_fields={#匹配域
            "hdr.ipv4.dstAddr": (dst_ip_addr, 32)#若hdr.ipv4.dstAddr与dst_ip_addr匹配则执行动作，32是掩码
        },
        action_name="MyIngress.ipv4_forward",#动作名
        action_params={#传入参数
            "dstAddr":dst_eth_addr,
            "port":WITCH_TO_HOST_PORT,
        })
    egress_sw.WriteTableEntry(table_entry)#将生成的匹配动作表项加入交换机




def readTableRules(p4info_helper, sw):
    """
    Reads the table entries from all tables on the switch.
    :param p4info_helper: the P4Info helper
    :param sw: the switch connection
    """
    print('\n----- Reading tables rules for %s -----' % sw.name)
    for response in sw.ReadTableEntries():
        for entity in response.entities:
            entry = entity.table_entry
            # TODO For extra credit, you can use the p4info_helper to translate
            #      the IDs in the entry to names

            print(entry)
            print('-----')



def printGrpcError(e):
    print("gRPC Error:", e.details(), end=' ')
    status_code = e.code()
    print("(%s)" % status_code.name, end=' ')
    traceback = sys.exc_info()[2]
    print("[%s:%d]" % (traceback.tb_frame.f_code.co_filename, traceback.tb_lineno))

def main(p4info_file_path, bmv2_file_path):
    # Instantiate a P4Runtime helper from the p4info file
    p4info_helper = p4runtime_lib.helper.P4InfoHelper(p4info_file_path)# P4InfoHelper工具类会读取并解析p4编译器编译得到的xxx.p4.p4info.txt
# bmv2_json_file_path即p4编译器编译得到的xxx.json
# txt文件中主要记录了p4程序的一些元信息，比如id等，json文件中则记载了具体的p4程序，比如stage，操作等，用于下发给交换机
    try:
        # Create a switch connection object for s1 and s2;
        # this is backed by a P4Runtime gRPC connection.
        # Also, dump all P4Runtime messages sent to switch to given txt files.
        s1 = p4runtime_lib.bmv2.Bmv2SwitchConnection(
            name='s1',
            address='127.0.0.1:50051',
            device_id=0,
            proto_dump_file='logs/s1-p4runtime-requests.txt')
        s2 = p4runtime_lib.bmv2.Bmv2SwitchConnection(
            name='s2',
            address='127.0.0.1:50052',
            device_id=1,
            proto_dump_file='logs/s2-p4runtime-requests.txt')

        s3 = p4runtime_lib.bmv2.Bmv2SwitchConnection(
            name='s3',
            address='127.0.0.1:50053',
            device_id=2,
            proto_dump_file='logs/s3-p4runtime-requests.txt')
        # Send master arbitration update message to establish this controller as
        # master (required by P4Runtime before performing any other write operation)
        s1.MasterArbitrationUpdate()
        s2.MasterArbitrationUpdate()
        s3.MasterArbitrationUpdate()
        # Install the P4 program on the switches
        s1.SetForwardingPipelineConfig(p4info=p4info_helper.p4info,
                                       bmv2_json_file_path=bmv2_file_path)
        print("Installed P4 Program using SetForwardingPipelineConfig on s1")
        s2.SetForwardingPipelineConfig(p4info=p4info_helper.p4info,
                                       bmv2_json_file_path=bmv2_file_path)
        print("Installed P4 Program using SetForwardingPipelineConfig on s2")

        s3.SetForwardingPipelineConfig(p4info=p4info_helper.p4info,
                                       bmv2_json_file_path=bmv2_file_path)
        print("Installed P4 Program using SetForwardingPipelineConfig on s3")

        # Write the rules that tunnel traffic from h1 to h2
        writeTunnelRules(p4info_helper, ingress_sw=s1, egress_sw=s2, tunnel_id=100,
                         dst_eth_addr="08:00:00:00:02:02", dst_ip_addr="10.0.2.2")


        # Write the rules that tunnel traffic from h2 to h1
        writeTunnelRules(p4info_helper, ingress_sw=s2, egress_sw=s1, tunnel_id=200,
                         dst_eth_addr="08:00:00:00:01:01", dst_ip_addr="10.0.1.1")


        # Write the rules that tunnel traffic from h11 to h22
        writeTunnelRules(p4info_helper, ingress_sw=s1, egress_sw=s2, tunnel_id=300,
                         dst_eth_addr="08:00:00:00:02:22", dst_ip_addr="10.0.2.22")


        # Write the rules that tunnel traffic from h22 to h11
        writeTunnelRules(p4info_helper, ingress_sw=s2, egress_sw=s1, tunnel_id=400,
                         dst_eth_addr="08:00:00:00:01:11", dst_ip_addr="10.0.1.11")


        # TODO Uncomment the following two lines to read table entries from s1 and s2
        readTableRules(p4info_helper, s1)
        readTableRules(p4info_helper, s2)
        readTableRules(p4info_helper, s3)#从S1、S2和S3读表项的操作

    except KeyboardInterrupt:
        print(" Shutting down.")
    except grpc.RpcError as e:
        printGrpcError(e)

    ShutdownAllSwitchConnections()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='P4Runtime Controller')
    parser.add_argument('--p4info', help='p4info proto in text format from p4c',
                        type=str, action="store", required=False,
                        default='./build/ecn.p4.p4info.txt')
    parser.add_argument('--bmv2-json', help='BMv2 JSON file from p4c',
                        type=str, action="store", required=False,
                        default='./build/ecn.json')
    args = parser.parse_args()

    if not os.path.exists(args.p4info):
        parser.print_help()
        print("\np4info file not found: %s\nHave you run 'make'?" % args.p4info)
        parser.exit(1)
    if not os.path.exists(args.bmv2_json):
        parser.print_help()
        print("\nBMv2 JSON file not found: %s\nHave you run 'make'?" % args.bmv2_json)
        parser.exit(1)
    main(args.p4info, args.bmv2_json)
